downloader/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('download/', views.download_view, name='download_view'),
]

youtube_downloader/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('downloader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

downloader/models.py
from django.db import models

# Create your models here.

downloader/forms.py
# forms.py
from django import forms

class DownloadForm(forms.Form):
    video_url = forms.URLField(label='Enter the YouTube video URL', max_length=200,)
    quality_choices = [('highest', 'Highest'), ('lowest', 'Lowest')]
    quality = forms.ChoiceField(choices=quality_choices, initial='highest', widget=forms.RadioSelect)

downloader/views.py
# views.py
import os
from django.shortcuts import render
from django.http import HttpResponse
from .forms import DownloadForm
from pytube import YouTube

def home(requset):
    return render(requset, 'index.html')

def download_view(request):
    if request.method == 'POST':
        form = DownloadForm(request.POST)
        if form.is_valid():
            video_url = form.cleaned_data['video_url']
            quality = form.cleaned_data['quality']

            try:
                # Create a YouTube object
                yt = YouTube(video_url)

                # Get the video title
                video_title = yt.title

                # Remove invalid characters from the video title
                valid_chars = '-_() abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
                video_title_cleaned = ''.join(c for c in video_title if c in valid_chars)

                if quality == "highest":
                    video_stream = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
                elif quality == "lowest":
                    video_stream = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').first()
                else:
                    return HttpResponse("Invalid quality selection")
                if video_stream is None:
                    return HttpResponse("No video stream found")

                # Ask user for download location (optional)
                # download_dir = filedialog.askdirectory(initialdir="D:/Downloader", title="Select Download Directory")
                # You may choose to use a default directory or prompt the user for one
                download_directory = os.path.join("D:\YoutubeVideoDownloader" )
                if not os.path.exists(download_directory):
                    os.makedirs(download_directory)

                # Download the video
                video_stream.download(output_path=download_directory, filename=f"{video_title_cleaned}.mp4")

                # Optionally, you can provide a link for the user to download the file
                download_link = f'<a href="YoutubeVideoDownloader/{video_title_cleaned}.mp4" download>Download Video</a>'
                return render(request, 'download_success.html', {'video_title_cleaned': video_title_cleaned})

            except Exception as e:
                return HttpResponse(f"An error occurred: {str(e)}")
    else:
        form = DownloadForm()
    return render(request, 'download_form.html', {'form': form},)

downloader/templates/download_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YouTube Video Downloader</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 720px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 30px;
        }
        form {
            text-align: center;
        }
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }
        button[type="submit"] {
            padding: 10px 20px;
            background-color: #2e6549;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        button[type="button"] {
            padding: 10px 20px;
            background-color: #1f6131;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s;
        }
        button[type="button"]:hover {
            background-color: #0056b3;
        }
        .error-message {
            color: red;
            font-size: 14px;
            margin-top: 10px;
        }
        .snackbar {
            display: none;
            position: fixed;
            left: 50%;
            transform: translateX(-50%);
            bottom: 20px;
            background-color: #f44336;
            color: white;
            padding: 16px;
            border-radius: 5px;
            z-index: 1;
        }
        li{
            color: red;
        }
        label{
            font-weight: bold;
        }
        #id_video_url{
            width: 315px;
            height: 45px;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>YouTube Video Downloader</h1>
        <form method="post" id="downloadForm">
            {% csrf_token %}
            <p><span id="erorr"></span></p>
            {{ form.as_p }}
            <button class="button" type="button" id="pasteButton">Show Video Details</button>
            <button type="submit">Download</button>
        </form>
        <div id="videoDetails">
            <h2><u> Video Details </u> </h2>
            <p><strong>Title: <br> </strong> <span id="title"></span></p><br>
            <p><strong>Thumbnail: <br> </strong> <img id="thumbnail" src="" alt="Thumbnail"></p> <br>
            <p><strong>Description: <br> </strong> <span id="description"></span></p><br>
        </div>
    </div>
    
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('pasteButton').addEventListener('click', function() {
            navigator.clipboard.readText()
                .then(function(text) {
                    // Call fetchVideoDetails function with the video URL from clipboard
                    fetchVideoDetails(text);
                })
                .catch(function(err) {
                    console.error('Failed to read clipboard contents:', err);
                });
        });
    
        // Function to fetch video details from the YouTube API
        function fetchVideoDetails(videoUrl) {
            // Extract video ID from the YouTube URL
            var videoId = extractVideoId(videoUrl);
            if (!videoId) {
                console.error('Invalid YouTube URL');
                document.getElementById('erorr').innerText = error;
                return;
            }
    
            // Construct the URL for fetching video details from YouTube API
            var apiKey = 'AIzaSyBtjE9hB_i1yDdk_tccdG64OvCTFHwd9Zs';
            var apiUrl = `https://www.googleapis.com/youtube/v3/videos?id=${videoId}&part=snippet&key=${apiKey}`;
    
            // Make a GET request to the YouTube API
            fetch(apiUrl)
                .then(function(response) {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(function(data) {
                    // Check if the response contains expected data
                    if (!data || !data.items || data.items.length === 0 || !data.items[0].snippet) {
                        throw new Error('Invalid response data');
                    }
    
                    // Extract title, thumbnail, and description from the response
                    var title = data.items[0].snippet.title;
                    var thumbnail = data.items[0].snippet.thumbnails.standard.url;
                    var description = data.items[0].snippet.description;
                    
                    // Display the fetched video details
                    document.getElementById('title').innerText = title;
                    document.getElementById('thumbnail').src = thumbnail;
                    document.getElementById('description').innerText = description;
    
                    // Show the video details section
                    document.getElementById('videoDetails').style.display = 'block';
                })
                .catch(function(err) {
                    console.error('Error fetching video details:', err);
                });
        }
    
        // Function to extract video ID from YouTube URL
        function extractVideoId(videoUrl) {
            var videoIdMatch = videoUrl.match(/(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|.*[&?&]v=))([^&?/]+)/i);
            return videoIdMatch ? videoIdMatch[1] : null;
        }
    });
    </script>
</body>
</html>

downloader/templates/download_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download Successful!</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        h1 {
            color: #333;
            margin-bottom: 20px;
        }
        p {
            color: #666;
            line-height: 1.6;
            margin-bottom: 15px;
        }
        .download-link {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        .download-link:hover {
            background-color: #151b15;
        }
        .rd-link {
            display: inline-block;
            padding: 10px 20px;
            background-color: #2b9220;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        .rd-link:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>

<div class="container">
    <h1>Download Successful!</h1>
    <p>Your video has been successfully downloaded.</p>
    <P> <strong> Video Name : {{video_title_cleaned}}</strong></P>
    <p>The video has been saved in the following folder:</p>
    <p><strong>D:/YoutubeVideoDownloader/</strong></p>

    <a target="_blank"  href="file:///D:/YoutubeVideoDownloader/" class="download-link" >Open Folder</a> 
    <a target="_self"  href="http://127.0.0.1:8000/" class="rd-link" >Download Another Video</a>
</div>

</body>
</html>

downloader/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YouTube Video Downloader</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        h1 {
            color: #333;
            margin-bottom: 20px;
        }
        p {
            color: #666;
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }
        button[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        .ads-container {
            margin-top: 20px;
        }
    </style>
</head>
<body>

<div class="container">
    <h1>Welcome to YouTube Video Downloader</h1>
    <p>Click Start Button to Start </p>

    <form method="post" action="{% url 'download_view' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Start</button>
    </form>

    <!-- Google AdSense Ad Code -->
    <div class="ads-container">
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8002393143036713"
            crossorigin="anonymous"></script>
        <ins class="adsbygoogle"
            style="display:block"
            data-ad-client="ca-pub-8002393143036713"
            data-ad-slot="6429201964"
            data-ad-format="auto"
            data-full-width-responsive="true"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
</div>
<div class="ads-container">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8002393143036713"
        crossorigin="anonymous"></script>
    <ins class="adsbygoogle"
        style="display:block"
        data-ad-client="ca-pub-8002393143036713"
        data-ad-slot="6429201964"
        data-ad-format="auto"
        data-full-width-responsive="true"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</div>
<div class="ads-container">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8002393143036713"
        crossorigin="anonymous"></script>
    <ins class="adsbygoogle"
        style="display:block"
        data-ad-client="ca-pub-8002393143036713"
        data-ad-slot="6429201964"
        data-ad-format="auto"
        data-full-width-responsive="true"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</div>

</body>
<footer style="text-align: center;
display: flex;
flex-direction: column;
justify-content: center;
align-items: center;">
    <h2>Made By Raihan </h2>
    <h1>Since 2024</h1>
</footer>
</html>